summary of numpy library:

numpy is a third-party module to deal with Arrays & matrices
numpy stands for numerical python

why use numpy:
numpy uses less memory
faster than "python list"
easy to use
numpy saves data side-by-side in a neat way

Homogeneous contains the same type object
Heterogeneous contains different type object

an array needs to be the same type data and can choose the required size
an array starts from an index of 0

(ndarray) stands for number of dimensional array which can be 0 1 2 3 4 or any number

In [ ]:
import numpy as np

my_list=[1,2,3,4,5]
my_array=np.array(my_list)

print(my_list) # print the contents of my_list
print(my_array) # print the contents of my_array

print("*" * 50)

print(type(my_list)) # show type for my_list
print(type(my_array)) #show type for my_array

print("*" * 50)

print(my_list[0]) # accessing elements
print(my_array[0]) # accessing elements

print("*" * 50)

a = np.array(10) # zero dimensional array
b = np.array([10, 20]) # one dimensional array
c = np.array( [ [1, 2],[3, 4] ] ) # two dimensional array
d = np.array( [ [ [5, 6], [7, 8] ],[ [9, 10],[11, 12] ] ] ) # three dimensional array

print(d[1][1][1]) # example : if index is 0 it takes the first dimension if index is 1 takes the next dimension and so on
print(d[1,1,1]) # same but simpler
print(d[1,1,-1]) # same but works with minus (-1)

print("*" * 50)

# Number Of Dimensions

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

print("*" * 50)

# Custom Dimensions

my_custom_array = np.array([1,2,3], ndmin=3) # create custom arrays and change the ndim in side of them
print(my_custom_array)
print(my_custom_array.ndim)
print(my_custom_array[0,0,0])


[1, 2, 3, 4, 5]
[1 2 3 4 5]
**************************************************
<class 'list'>
<class 'numpy.ndarray'>
**************************************************
1
1
**************************************************
12
12
12
**************************************************
0
1
2
3
**************************************************
[[[1 2 3]]]
3
1


Numpy compare data location and type:

in the list all type of data stays the same type
but in the array all of the data becomes the easiest type of data to read

In [ ]:
import numpy as np

my_list = [1, 2, 3, 4, 5]
my_array = np.array([1, 2, 3, 4, 5])

print(my_list[0])
print(my_list[1])

print(my_array[0])
print(my_array[1])

print("*" * 50)
# check id of list and array (list changes) (array stays the same)

print(id(my_list[0]))
print(id(my_list[1]))

print(id(my_array[0]))
print(id(my_array[1]))

print("*" * 50)

my_list_of_data = [1, 2, "A", "B", True, 10.50] # stays the same value
my_array_of_data = np.array([1, 2, "A", "B", True, 10.50]) # makes every value a string

print(my_list_of_data)
print(my_array_of_data)

print("*" * 50)
# same data (1) but array is str and list is int

print(my_list_of_data[0])
print(my_array_of_data[0])

print(type(my_list_of_data[0]))
print(type(my_array_of_data[0]))

print("*" * 50)
# ------------ data 2 --------------

my_list_of_data_two = [1, 2, "A", "B", True, 10.50] # stays the same value
my_array_of_data_two = np.array([1, 2]) # if the same type of data stays the same type

print(my_list_of_data_two)
print(my_array_of_data_two)

print("*" * 50)

print(my_list_of_data_two[0])
print(my_array_of_data_two[0])

print(type(my_list_of_data_two[0]))
print(type(my_array_of_data_two[0]))




1
2
1
2
**************************************************
140722212926376
140722212926408
2716169536304
2716169536304
**************************************************
[1, 2, 'A', 'B', True, 10.5]
['1' '2' 'A' 'B' 'True' '10.5']
**************************************************
1
1
<class 'int'>
<class 'numpy.str_'>


numpy performance and memory use:

list takes much more time when looping more items
array is much much faster when looping items

list takes more bytes of memory to calculate
array takes much less bytes of the memory to calculate

In [52]:
import numpy as np
import time
import sys

# --------- calculating time for each calculation of loops ---------- #

# elements = 15000000

# my_list1 = range(elements)
# my_list2= range(elements)

# my_array1= np.arange(elements)
# my_array2= np.arange(elements)

# list_start = time.time()
# list_result = [(n1 + n2) for n1, n2 in zip(my_list1, my_list2) ]
# print(f"List Time: {time.time() - list_start}")

# print(list_result)


# array_start = time.time()
# array_result = my_array1 + my_array2
# print(f"array Time: {time.time() - array_start}")

# print(array_result)

# -------- calculating size --------- #

# takes less memory to calculate
my_array = np.arange(100)

print(my_array.itemsize) # how many bytes it takes
print(my_array.size)
print(f"All Bytes: {my_array.itemsize * my_array.size}")

print("*" * 50)

# takes more memory to calculate
my_list = range(100)

print(sys.getsizeof(1))
print(len(my_list))
print(f"All Bytes: {sys.getsizeof(1) * len(my_list)}")



8
100
All Bytes: 800
**************************************************
28
100
All Bytes: 2800


Array slicing:


In [20]:
import numpy as np

# Slicing => [Start:End:Steps] Not Encluding End

a = np.array(["A", "B", "C", "D", "E", "F"])

print(a.ndim)
print(a[1])

print("*" * 50)

print(a[1:4])
print(a[:4])
print(a[2:])

print("*" * 50)

b = np.array([["A", "B", "X"],["C", "D", "Y"],["E", "F", "Z"],["M", "N", "O"]])

print(b.ndim)
print(b[1])

print("*" * 50)

print(b[0:3])

print("*" * 50)

print(b[:3, :2])

print("*" * 50)

print(b[:3, :2])

1
B
**************************************************
['B' 'C' 'D']
['A' 'B' 'C' 'D']
['C' 'D' 'E' 'F']
**************************************************
2
['C' 'D' 'Y']
**************************************************
[['A' 'B' 'X']
 ['C' 'D' 'Y']
 ['E' 'F' 'Z']]
**************************************************
[['A' 'B']
 ['C' 'D']
 ['E' 'F']]
**************************************************
[['A' 'B']
 ['C' 'D']
 ['E' 'F']]


Data Types And Control Array

----------------------------------
https://numpy.org/devdocs/user/basics.types.html

https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html#specifying-and-constructing-data-types

------------------------

'?' boolean

'b' (signed) byte

'B' unsigned byte

'i' (signed) integer

'u' unsigned integer

'f' floating-point

'c' complex-floating point

'm' timedelta

'M' datetime

'O' (Python) objects

'S', 'a' zero-terminated bytes (not recommended)

'U' Unicode string

'V' raw data (void)


In [6]:
import numpy as np

# Show Array Data Type

my_array1 = np.array([1, 2, 3])
my_array2 = np.array([1.5, 20.15, 3.601])
my_array3 = np.array(["Osama_Elzero", "B", "Ahmed"])

print(my_array1.dtype)
print(my_array2.dtype)
print(my_array3.dtype)

print("*" * 50)

# Create Array With Specific Data Type

my_array4 = np.array([1, 2, 3], dtype=float) # float Or 'float' Or 'f'
my_array5 = np.array([1.5, 20.15, 3.601], dtype=int) # int Or 'int' Or 'i'
# my_array6 = np.array(["Osama_Elzero", "B", "Ahmed"], dtype=int) # Value Error

print(my_array4.dtype)
print(my_array5.dtype)
# print(my_array6.dtype)

print("*" * 50)

# Change Data Type Of Existing Array

my_array7 = np.array([0, 1, 2, 3, 0, 4])
print(my_array7.dtype)
print(my_array7)

print("*" * 50)

my_array7 = my_array7.astype('float')
print(my_array7.dtype)
print(my_array7)

print("*" * 50)

my_array7 = my_array7.astype('bool')
print(my_array7.dtype)
print(my_array7)

print("*" * 50)

# Test Capacity

my_array8 = np.array([100, 200, 300, 400], dtype='f')
print(my_array8.dtype)
print(my_array8[0].itemsize) # 4 Bytes

my_array8 = my_array8.astype('float') # Change To Float64
print(my_array8.dtype)
print(my_array8[0].itemsize) # 8 Bytes


int64
float64
<U12
**************************************************
float64
int64
**************************************************
int64
[0 1 2 3 0 4]
**************************************************
float64
[0. 1. 2. 3. 0. 4.]
**************************************************
bool
[False  True  True  True False  True]
**************************************************
float32
4
float64
8
